[package]
name = "crumble"
version = "0.1.0"
edition = "2024"

[dependencies]
crumble-sql = { path = "../crumble-sql" }
crumble-ir = { path = "../crumble-ir" }
crumble-opt = { path = "../crumble-opt" }
crumble-storage = { path = "../crumble-storage" }
crumble-exec = { path = "../crumble-exec" }
crumble-planner = { path = "../crumble-planner" }